schema = 1
project = "daukle/example-node-hello-dependency"
version = "1.0.0"

[modules]

[resolvers.github]
url = "https://raw.githubusercontent.com/daukle/daukle/1f515141e06d16eace718a45944a39933611fa39/plugins/github-releases.lua"
sha256 = "3789865c266eb53fafcf7300d77a24461170c615195d92d0ddf88078c556e23e"

[plugins]
node = { resolver = "github", coordinate = "daukle/node@^1.0.0" }

[toolchains.node]
version = ">=22.15.0"
entry = "src/main.mjs"

[toolchains.node.packages]
is-even = "1.0.0"
